services:
  gymbot:
    build:
      context: .
    volumes:
      - /home/smmulas/gymbot/gym.db:/app/gym.db
    environment:
      - TOKEN=${TOKEN}  # Esto toma el valor del archivo .env
    restart: unless-stopped
